// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8r7ojBHEs03t-JhJUZ2z6LTckZsQmPI',
    appId: '1:765560569666:web:ca88785798d1cc433312db',
    messagingSenderId: '765560569666',
    projectId: 'minhas-financas-app-d1069',
    authDomain: 'minhas-financas-app-d1069.firebaseapp.com',
    storageBucket: 'minhas-financas-app-d1069.firebasestorage.app',
    measurementId: 'G-Z8XHB3C5LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL0wGSdGb-kuObExUNSZXA7ACUM_v0Qs',
    appId: '1:765560569666:android:078dbd910329b5923312db',
    messagingSenderId: '765560569666',
    projectId: 'minhas-financas-app-d1069',
    storageBucket: 'minhas-financas-app-d1069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTptzKy6OpuP-I8-hZBmt6miPgiEGNBc',
    appId: '1:765560569666:ios:a43e50298c7bd3123312db',
    messagingSenderId: '765560569666',
    projectId: 'minhas-financas-app-d1069',
    storageBucket: 'minhas-financas-app-d1069.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHTptzKy6OpuP-I8-hZBmt6miPgiEGNBc',
    appId: '1:765560569666:ios:a43e50298c7bd3123312db',
    messagingSenderId: '765560569666',
    projectId: 'minhas-financas-app-d1069',
    storageBucket: 'minhas-financas-app-d1069.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_8r7ojBHEs03t-JhJUZ2z6LTckZsQmPI',
    appId: '1:765560569666:web:562371950c8c49273312db',
    messagingSenderId: '765560569666',
    projectId: 'minhas-financas-app-d1069',
    authDomain: 'minhas-financas-app-d1069.firebaseapp.com',
    storageBucket: 'minhas-financas-app-d1069.firebasestorage.app',
    measurementId: 'G-F055FCPXJ2',
  );
}
